{% set name = "spaghetti" %}
{% set version = "1.6.10" %}
{% set sha256 = "c4f8c61e055f82ed8495e8f3c5c34c629cab0c4b62e5ef643a0ec117b8810e9b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - scipy >=1.0
    - numpy >=1.3
    - pandas >=1.0
    - libpysal
    - esda
    - rtree

test:
  imports:
    - spaghetti
  # --> comment from @ocefpaf <-- see conda-forge/libpysal-feedstock#8
  # pip check is not smart enough to know that an import name is not the package name :-(
  # commands:
  #  - pip check
  # requires:
  #  - pip

about:
  home: http://pysal.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'SPAtial GrapHs: nETworks, Topology, & Inference'
  description: |
    Spaghetti is an open-source Python library for the analysis
    of network-based spatial data. Originating from the network 
    module in [PySAL](http://pysal.org) (Python Spatial Analysis Library), 
    it is under active development for the inclusion of 
    newly-proposed methods for building graph-theoretic 
    networks and the analysis of network events.
  doc_url: https://pysal.org/spaghetti/
  dev_url: http://github.com/pysal/spaghetti

extra:
  recipe-maintainers:
    - jGaboardi
    - knaaptime
