{% set name = "spaghetti" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d919224e94d242e17bda700e5f14a227f884594a91b0103a5f01ced3f2b176f7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python>=3
    - pip
  run:
    - python>=3
    - scipy>=0.11
    - numpy>=1.3
    - pandas
    - esda
    - rtree

test:
  imports:
    - spaghetti

about:
  home: http://github.com/pysal/spaghetti
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'SPAtial GrapHs: nETworks, Topology, & Inference'
  description: |
    Spaghetti is an open-source python library for the analysis 
    of network-based spatial data. Originating from the network 
    module in [PySAL](http://pysal.org) (Python Spatial Analysis Library), 
    it is under active development for the inclusion of 
    newly proposed methods for building graph-theoretic 
    networks and the analysis of network events.
  doc_url: https://pysal-spaghetti.readthedocs.io
  dev_url: http://github.com/pysal/spaghetti

extra:
  recipe-maintainers:
    - jGaboardi
    - knaaptime
